require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/book_collections", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BookCollection. As you add validations to BookCollection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BookCollection.create! valid_attributes
      get book_collections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      book_collection = BookCollection.create! valid_attributes
      get book_collection_url(book_collection)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_book_collection_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      book_collection = BookCollection.create! valid_attributes
      get edit_book_collection_url(book_collection)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BookCollection" do
        expect {
          post book_collections_url, params: { book_collection: valid_attributes }
        }.to change(BookCollection, :count).by(1)
      end

      it "redirects to the created book_collection" do
        post book_collections_url, params: { book_collection: valid_attributes }
        expect(response).to redirect_to(book_collection_url(BookCollection.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BookCollection" do
        expect {
          post book_collections_url, params: { book_collection: invalid_attributes }
        }.to change(BookCollection, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post book_collections_url, params: { book_collection: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested book_collection" do
        book_collection = BookCollection.create! valid_attributes
        patch book_collection_url(book_collection), params: { book_collection: new_attributes }
        book_collection.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the book_collection" do
        book_collection = BookCollection.create! valid_attributes
        patch book_collection_url(book_collection), params: { book_collection: new_attributes }
        book_collection.reload
        expect(response).to redirect_to(book_collection_url(book_collection))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        book_collection = BookCollection.create! valid_attributes
        patch book_collection_url(book_collection), params: { book_collection: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested book_collection" do
      book_collection = BookCollection.create! valid_attributes
      expect {
        delete book_collection_url(book_collection)
      }.to change(BookCollection, :count).by(-1)
    end

    it "redirects to the book_collections list" do
      book_collection = BookCollection.create! valid_attributes
      delete book_collection_url(book_collection)
      expect(response).to redirect_to(book_collections_url)
    end
  end
end
