require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/book2s", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Book2. As you add validations to Book2, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Book2.create! valid_attributes
      get book2s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      book2 = Book2.create! valid_attributes
      get book2_url(book2)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_book2_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      book2 = Book2.create! valid_attributes
      get edit_book2_url(book2)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Book2" do
        expect {
          post book2s_url, params: { book2: valid_attributes }
        }.to change(Book2, :count).by(1)
      end

      it "redirects to the created book2" do
        post book2s_url, params: { book2: valid_attributes }
        expect(response).to redirect_to(book2_url(Book2.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Book2" do
        expect {
          post book2s_url, params: { book2: invalid_attributes }
        }.to change(Book2, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post book2s_url, params: { book2: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested book2" do
        book2 = Book2.create! valid_attributes
        patch book2_url(book2), params: { book2: new_attributes }
        book2.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the book2" do
        book2 = Book2.create! valid_attributes
        patch book2_url(book2), params: { book2: new_attributes }
        book2.reload
        expect(response).to redirect_to(book2_url(book2))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        book2 = Book2.create! valid_attributes
        patch book2_url(book2), params: { book2: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested book2" do
      book2 = Book2.create! valid_attributes
      expect {
        delete book2_url(book2)
      }.to change(Book2, :count).by(-1)
    end

    it "redirects to the book2s list" do
      book2 = Book2.create! valid_attributes
      delete book2_url(book2)
      expect(response).to redirect_to(book2s_url)
    end
  end
end
