require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/book3s", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Book3. As you add validations to Book3, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Book3.create! valid_attributes
      get book3s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      book3 = Book3.create! valid_attributes
      get book3_url(book3)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_book3_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      book3 = Book3.create! valid_attributes
      get edit_book3_url(book3)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Book3" do
        expect {
          post book3s_url, params: { book3: valid_attributes }
        }.to change(Book3, :count).by(1)
      end

      it "redirects to the created book3" do
        post book3s_url, params: { book3: valid_attributes }
        expect(response).to redirect_to(book3_url(Book3.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Book3" do
        expect {
          post book3s_url, params: { book3: invalid_attributes }
        }.to change(Book3, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post book3s_url, params: { book3: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested book3" do
        book3 = Book3.create! valid_attributes
        patch book3_url(book3), params: { book3: new_attributes }
        book3.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the book3" do
        book3 = Book3.create! valid_attributes
        patch book3_url(book3), params: { book3: new_attributes }
        book3.reload
        expect(response).to redirect_to(book3_url(book3))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        book3 = Book3.create! valid_attributes
        patch book3_url(book3), params: { book3: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested book3" do
      book3 = Book3.create! valid_attributes
      expect {
        delete book3_url(book3)
      }.to change(Book3, :count).by(-1)
    end

    it "redirects to the book3s list" do
      book3 = Book3.create! valid_attributes
      delete book3_url(book3)
      expect(response).to redirect_to(book3s_url)
    end
  end
end
